import turtle as trtl
screen=trtl.Screen() 
painter = trtl.Turtle()

painter.speed(1000)

#background
painter.fillcolor("gray")
painter.begin_fill()
painter.penup()
painter.goto(-250, 25)
painter.pendown()
painter.goto(250, 25)
painter.goto(250, -250)
painter.goto(-250, -250)
painter.goto(-250, 25)
painter.end_fill()
painter.fillcolor("#75A2BF")
painter.begin_fill()
painter.goto(-250, 250)
painter.goto(250, 250)
painter.goto(250, 25)
painter.goto(-250, 25)
painter.end_fill()

#background object
painter.pencolor("black")
painter.fillcolor("#D3D3D3")
painter.penup() 
painter.goto(-25,25)
painter.pendown() 
painter.begin_fill() 
painter.goto(-25,250)
painter.goto(-250,250)
painter.goto(-250,25)
painter.goto(-25,25)
painter.end_fill() 
painter.penup() 
painter.goto(-80,25)
painter.pendown()
painter.fillcolor("#654321")
painter.begin_fill() 
painter.goto(-80,250)
painter.goto(-200,250)
painter.goto(-200,25)
painter.goto(-80,25)
painter.end_fill() 
painter.penup() 
painter.goto(-100,150)
painter.pendown() 
painter.fillcolor("#BBA14F")
painter.shape("circle")
painter.stamp() 
painter.shape("arrow")
painter.penup() 
painter.goto(40,25)
painter.pendown() 
painter.fillcolor("#D3D3D3")
painter.begin_fill() 
painter.goto(250,25)
painter.goto(250,250)
painter.goto(40,250)
painter.goto(40,25)
painter.end_fill() 
painter.penup() 
painter.goto(80,140)
painter.pendown() 
painter.fillcolor("#ADD8E6")
painter.begin_fill() 
painter.goto(230,140)
painter.goto(230,250)
painter.goto(80,250)
painter.goto(80,140)
painter.end_fill()

#Create Box
painter.pencolor("#654321")

#Bottom and Back
painter.fillcolor("#C4A484")
painter.penup()
painter.goto(0, 0)
painter.pendown()
painter.begin_fill()
painter.penup()
painter.goto(95, 0)
painter.pendown()
painter.goto(50, -50)
painter.end_fill()
painter.penup()
painter.goto(0, 0)
painter.pendown()
painter.begin_fill()
painter.goto(0, 95)
painter.goto(95, 95)
painter.goto(95, 0)
painter.end_fill()

#Front Face
painter.fillcolor("#C4A484")
painter.begin_fill()
painter.penup()
painter.goto(-50, -50)
painter.pendown()
painter.goto(-50, 50)
painter.goto(50, 50)
painter.goto(50, -50)
painter.goto(-50, -50)
painter.end_fill()

#sides
painter.penup()
painter.goto(0, 95)
painter.pendown()
painter.goto(-50, 50)
painter.penup()
painter.goto(95, 95)
painter.pendown()
painter.goto(50, 50)

#color help
painter.begin_fill()
painter.penup()
painter.goto(0, 95)
painter.pendown()
painter.goto(-50, 50)
painter.goto(0, 50)
painter.goto(0, 95)
painter.end_fill()

#detail
painter.pencolor("black")
painter.penup() 
painter.goto(40,40)
painter.pendown() 
painter.shapesize(0.5)
painter.shape("square")
painter.stamp() 
painter.penup() 
painter.goto(25,40)
painter.pendown() 
painter.stamp()
painter.penup() 
painter.goto(-40,35)
painter.right(270)
painter.pendown() 
painter.shapesize(0.7)
painter.shape("arrow")
painter.stamp() 
painter.penup() 
painter.goto(20,32)
painter.pendown()  
painter.goto(45,32)
painter.goto(45,30)
painter.goto(20,30)
painter.goto(20,32) 
painter.pencolor("#C4A484")
painter.fillcolor("#C4A484")
painter.penup() 
painter.goto(0,0)
painter.pendown() 

painter.hideturtle() 

#Save Screen
wn = trtl.Screen()
wn.mainloop()